export const data = [
  {
    id: 882,
    job_id: "rngl181",
    job_title: "Admin Finance",
    company: "CITRANET (PT Jembatan Citra Nusantara)",
    category: "Finance Accounting",
    location: "Kapanewon Wonosari, Gunungkidul, DI Yogyakarta, Indonesia",
    work_type: "Kontrak",
    working_type: "Tidak ditampilkan",
    salary: "Rp2jt-Rp3jt",
    experience: "Kurang dari setahun",
    skills: "Microsoft Excel",
    study_requirement: "SMA/SMK",
    link: "https://glints.com/id/opportunities/jobs/admin-finance/a55dab63-8506-4263-9c9c-359879526443?utm_referrer=explore",
    link_image:
      "https://images.glints.com/unsafe/glints-dashboard.s3.amazonaws.com/company-logo/931eb47322dfee14563516a3bdf1e54d.jpeg",
  },
  {
    id: 883,
    job_id: "rngl182",
    job_title: "Administrasi Finance",
    company: "CITRANET (PT Jembatan Citra Nusantara)",
    category: "Corporate Finance",
    location: "Kapanewon Bantul, Bantul, DI Yogyakarta, Indonesia",
    work_type: "Kontrak",
    working_type: "Tidak ditampilkan",
    salary: "Rp2jt-Rp3jt",
    experience: "Kurang dari setahun",
    skills: "Microsoft Excel, Keuangan Perusahaan",
    study_requirement: "SMA/SMK",
    description:
      "Melakukan pengelolaan keuangan;, Melakukan pekerjaan administrasi perkantoran.",
    link: "https://glints.com/id/opportunities/jobs/administrasi-finance/323568b1-b2e7-4714-895e-2c7f1e8aff09?utm_referrer=explore",
    link_image:
      "https://images.glints.com/unsafe/glints-dashboard.s3.amazonaws.com/company-logo/931eb47322dfee14563516a3bdf1e54d.jpeg",
  },
  {
    id: 884,
    job_id: "rngl183",
    job_title: "Technical Fiber Optic",
    company: "CITRANET (PT Jembatan Citra Nusantara)",
    category: "Fiber Optic Networks",
    location: "Purwokerto Selatan, Banyumas, Jawa Tengah, Indonesia",
    work_type: "Kontrak",
    working_type: "Tidak ditampilkan",
    salary: "Rp2jt-Rp2,5jt",
    experience: "Kurang dari setahun",
    skills: "Jaringan Nirkabel",
    study_requirement: "SMA/SMK",
    description:
      "Memahami end to end proses instalasi jaringan fiber optik dan wireless, Berani untuk memanjat selama proses instalasi, Melakukan komunikasi yang baik terhadap pelanggan selama  proses instalasi, Melakukan konfigurasi awal untuk pemasangan jaringan",
    link: "https://glints.com/id/opportunities/jobs/technical-fiber-optic/cb283b19-d5c1-4b85-a819-7f23dc10660b?utm_referrer=explore",
    link_image:
      "https://images.glints.com/unsafe/glints-dashboard.s3.amazonaws.com/company-logo/931eb47322dfee14563516a3bdf1e54d.jpeg",
  },
  {
    id: 885,
    job_id: "rngl184",
    job_title: "Network Operation Center",
    company: "CITRANET (PT Jembatan Citra Nusantara)",
    category: "Network Administration",
    location: "Kapanewon Depok, Sleman, DI Yogyakarta, Indonesia",
    work_type: "Kontrak",
    working_type: "Tidak ditampilkan",
    salary: "Rp2,5jt-Rp3jt",
    experience: "Kurang dari setahun",
    skills:
      "Administrasi Jaringan, Jaringan IP, Jaringan, Jaringan Komputer, Konfigurasi Router, Cisco, Keterampilan Komunikasi",
    study_requirement: "SMA/SMK",
    description:
      "Menangani maintance dan kendala terkait jaringan, Melakukan follow up kepada pelanggan, untuk menjalin hubungan baik, End to end proses konfigurasi jaringan, Bekerja sama dengan tim yang lain untuk mengidentifikasi masalah yang berkemungkinan terjadi",
    link: "https://glints.com/id/opportunities/jobs/network-operation-center/39059191-ba25-4589-a222-2ff8c80ab54b?utm_referrer=explore",
    link_image:
      "https://images.glints.com/unsafe/glints-dashboard.s3.amazonaws.com/company-logo/931eb47322dfee14563516a3bdf1e54d.jpeg",
  },
  {
    id: 886,
    job_id: "rngl185",
    job_title: "Pengajar Fulltime Kimia (Edulab Balikpapan)",
    company: "Edulab Indonesia",
    category: "Interpersonal Communication",
    location: "Balikpapan Tengah, Balikpapan, Kalimantan Timur, Indonesia",
    work_type: "Penuh Waktu",
    working_type: "Tidak ditampilkan",
    salary: "Rp3jt-Rp3,5jt",
    experience: "Kurang dari setahun",
    skills: "Kemampuan Komunikasi, Komunikasi Interpersonal, Pengajaran",
    study_requirement: "Sarjana (S1)",
    link: "https://glints.com/id/opportunities/jobs/pengajar-fulltime-kimia-edulab-balikpapan/6089ae56-1ee4-40ea-baf5-b56fbfe83829?utm_referrer=explore",
    link_image:
      "https://images.glints.com/unsafe/glints-dashboard.s3.amazonaws.com/company-logo/40f55547435c926834c3ebba84d46121.png",
  },
  {
    id: 887,
    job_id: "rngl186",
    job_title: "Call Center/IT Helpdesk",
    company: "CITRANET (PT Jembatan Citra Nusantara)",
    category: "Computer Networking",
    location: "Kartasura, Sukoharjo, Jawa Tengah, Indonesia",
    work_type: "Kontrak",
    working_type: "Tidak ditampilkan",
    salary: "Rp2,2jt-Rp2,7jt",
    experience: "Kurang dari setahun",
    skills:
      "Kemampuan Komunikasi, Jaringan Komputer, Kemampuan Menggunakan Komputer, Keterampilan Komunikasi",
    study_requirement: "SMA/SMK",
    description:
      "Menjawab segala pertanyaan dan keluhan dari pelanggan secara digital, Menyatat dan menyampaikan keluhan dari pelanggan ke tim untuk di tindak lanjuti, Pembuatan laporan dari permasalahan yang telah di atasi untuk record, Memberikan solusi yang masuk akal ",
    link: "https://glints.com/id/opportunities/jobs/call-center-it-helpdesk/c583d859-15dd-4f45-b112-3990b716c262?utm_referrer=explore",
    link_image:
      "https://images.glints.com/unsafe/glints-dashboard.s3.amazonaws.com/company-logo/931eb47322dfee14563516a3bdf1e54d.jpeg",
  },
  {
    id: 888,
    job_id: "rngl187",
    job_title: "Konsultan",
    company: "Rumah Halal Indonesia",
    category: "Google SketchUp",
    location: "Ciomas, Bogor, Jawa Barat, Indonesia",
    work_type: "Penuh Waktu",
    working_type: "Tidak ditampilkan",
    salary: "Tidak ditampilkan",
    experience: "Kurang dari setahun",
    skills: "AutoCAD, Kemampuan Komunikasi, Google SketchUp",
    study_requirement: "Sarjana (S1)",
    description:
      "Menghitung RAB, Time Schedule dan Kurva S., Memilih alat dan bahan sesuai spesifikasi pekerjaan., Menetapkan harga pokok., Melakukan perhitungan MTO (Material Take Off) dan Bill of Quantity (BoQ) untuk keperluan proyek.",
    link: "https://glints.com/id/opportunities/jobs/konsultan/4dcc603c-3542-4a20-a19c-3d2b465b3937?utm_referrer=explore",
    link_image:
      "https://images.glints.com/unsafe/glints-dashboard.s3.amazonaws.com/company-logo/1a209e2111a2d2aa519da2a3f7276163.jpg",
  },
  {
    id: 889,
    job_id: "rngl188",
    job_title: "Fashion Designer Internship",
    company: "Makhtab Fashion",
    category: "Positive Attitude",
    location: "Ciputat, Tangerang Selatan, Banten, Indonesia",
    work_type: "Paruh Waktu",
    working_type: "Tidak ditampilkan",
    salary: "Tidak ditampilkan",
    experience: "Kurang dari setahun",
    skills: "Manajemen Pengetahuan, Sikap Positif",
    study_requirement: "SMA/SMK",
    link: "https://glints.com/id/opportunities/jobs/fashion-designer-internship/c6862d37-368e-4968-90d1-0a58713536a9?utm_referrer=explore",
    link_image:
      "https://images.glints.com/unsafe/glints-dashboard.s3.amazonaws.com/company-logo/94e1920deea90af4cc685cbbaa68ccc2.png",
  },
  {
    id: 890,
    job_id: "rngl189",
    job_title: "Truck Mechanic (Jawa Timur)",
    company: "PT. Dayaguna Motor Indonesia",
    category: "Mechanical Engineering",
    location: "Tambaksari, Surabaya, Jawa Timur, Indonesia",
    work_type: "Penuh Waktu",
    working_type: "Tidak ditampilkan",
    salary: "Tidak ditampilkan",
    experience: "Kurang dari setahun",
    skills: "Mekanik, Teknik Otomotif, Teknik Mekanik",
    study_requirement: "SMA/SMK",
    description:
      "P r i a, usia maksimal 30 tahun., Berdomisili di Jawa Timur & sekitarnya., Memiliki pengalaman di bidang Otomotif (diutamakan pengalaman di kendaraan Diesel)., Memiliki pengalaman otomotif 2W dipersilakan melamar., Bersedia bekerja shift., Bersedia ditemp",
    link: "https://glints.com/id/opportunities/jobs/truck-mechanic-jawa-timur/e8d7bee4-5811-48f7-9dd2-2b64ae35e659?utm_referrer=explore",
    link_image:
      "https://images.glints.com/unsafe/glints-dashboard.s3.amazonaws.com/company-logo/723c91c71c26a742fd42fcae6303d091.png",
  },
  {
    id: 891,
    job_id: "rngl190",
    job_title: "Interior Designer",
    company: "Homiku Living",
    category: "Google SketchUp",
    location: "Ciputat, Tangerang Selatan, Banten, Indonesia",
    work_type: "Penuh Waktu",
    working_type: "Tidak ditampilkan",
    salary: "Rp2,4jt-Rp2,5jt",
    experience: "Kurang dari setahun",
    skills: "Desain Kreatif, Desain Interior, Google SketchUp",
    study_requirement: "Sarjana (S1)",
    description:
      "Wanita berhijab (max 27 tahun)., Fresh Graduate., Berpengalaman diutamakan., Jujur dan berdedikasi, Menguasai sketchup + vray + cad, Memiliki wawasan dan teori yang baik terkait dunia interior., Kreatif dan inovatif, Menguasai photoshop + sosial media diu",
    link: "https://glints.com/id/opportunities/jobs/interior-designer/36b92362-ea88-47bf-909b-9b377c6aee18?utm_referrer=explore",
    link_image:
      "https://images.glints.com/unsafe/glints-dashboard.s3.amazonaws.com/company-logo/af037c54194b4062b9695b10aab20b5c.png",
  },
  {
    id: 892,
    job_id: "rngl191",
    job_title: "Intern QC & Packing (Paid Intern)",
    company: "Vherkudara Eyewear",
    category: "Teliti Dan Cekatan",
    location: "Kapanewon Depok, Sleman, DI Yogyakarta, Indonesia",
    work_type: "Magang",
    working_type: "Tidak ditampilkan",
    salary: "Tidak ditampilkan",
    experience: "Kurang dari setahun",
    skills: "Tidak ditampilkan",
    study_requirement: "SMA/SMK",
    link: "https://glints.com/id/opportunities/jobs/intern-qc-and-packing-paid-intern/28f7bc5a-141a-41a5-aa32-45c3d64ecb5c?utm_referrer=explore",
    link_image:
      "https://images.glints.com/unsafe/glints-dashboard.s3.amazonaws.com/company-logo/2f3ed3ae3997c51aed28b0fc9cebf55a.jpeg",
  },
  {
    id: 893,
    job_id: "rngl192",
    job_title: "Store Crew Five Monkeys",
    company: "Gama Culinary",
    category: "Communication Skills",
    location: "Cempaka Putih, Jakarta Pusat, DKI Jakarta, Indonesia",
    work_type: "Penuh Waktu",
    working_type: "Tidak ditampilkan",
    salary: "Tidak ditampilkan",
    experience: "Kurang dari setahun",
    skills: "Kerja Tim, Kemampuan Komunikasi, Keterampilan Pemecahan Masalah",
    study_requirement: "SMA/SMK",
    description:
      "Bersedia ditempatkan di outlet Five Monkeys yang ada di DKI Jakarta, Pria / Wanita, Usia Maksimal 28 Tahun, Berpengalaman di bidang F&B lebih diminati, Berpenampilan menarik dan komunikatif, Memiliki integritas tinggi, Berdomisili di DKI Jakarta dan sekit",
    link: "https://glints.com/id/opportunities/jobs/store-crew-five-monkeys/6cd38793-2040-4551-a857-8713281db6c8?utm_referrer=explore",
    link_image:
      "https://images.glints.com/unsafe/glints-dashboard.s3.amazonaws.com/company-logo/7bcb1b47a4433559fb4f1fa4ad7d6109.jpg",
  },
  {
    id: 894,
    job_id: "rngl193",
    job_title: "Promotor (Medan Pekanbaru Palembang)",
    company: "PT Arkana Advance Technology (Bang Jamin)",
    category: "Promotor",
    location: "Setiabudi, Jakarta Selatan, DKI Jakarta, Indonesia",
    work_type: "Penuh Waktu",
    working_type: "Tidak ditampilkan",
    salary: "Tidak ditampilkan",
    experience: "Kurang dari setahun",
    skills: "Interpersonal Skills",
    study_requirement: "SMA/SMK",
    description:
      "Pria/Wanita, Usia 18-40 tahun, Pendidikan min. SMA/sederajat, Sehat jasmani dan rohani, Memiliki keterampilan interpersonal yang baik, Mahir menggunakan gadget dan aplikasi online, Memiliki kendaraan motor dan SIM C, Handle area :",
    link: "https://glints.com/id/opportunities/jobs/promotor-medan-pekanbaru-palembang/e18fb6b6-7133-4e81-a32d-fe59660f0084?utm_referrer=explore",
    link_image:
      "https://images.glints.com/unsafe/glints-dashboard.s3.amazonaws.com/company-logo/ad03feb592aafe65d3c4d592b478800a.jpg",
  },
  {
    id: 895,
    job_id: "rngl194",
    job_title: "Promotor (Bandung Semarang Surabaya)",
    company: "PT Arkana Advance Technology (Bang Jamin)",
    category: "Promotor",
    location: "Sukajadi, Bandung, Jawa Barat, Indonesia",
    work_type: "Penuh Waktu",
    working_type: "Tidak ditampilkan",
    salary: "Tidak ditampilkan",
    experience: "Kurang dari setahun",
    skills: "Interpersonal Skills",
    study_requirement: "SMA/SMK",
    description:
      "Pria/Wanita, Usia 18-40 tahun, Pendidikan min. SMA/sederajat, Sehat jasmani dan rohani, Memiliki keterampilan interpersonal yang baik, Mahir menggunakan gadget dan aplikasi online, Memiliki kendaraan motor dan SIM C, Handle untuk area :",
    link: "https://glints.com/id/opportunities/jobs/promotor-bandung-semarang-surabaya/fd611c1c-b761-4b3c-b928-a19000d87876?utm_referrer=explore",
    link_image:
      "https://images.glints.com/unsafe/glints-dashboard.s3.amazonaws.com/company-logo/ad03feb592aafe65d3c4d592b478800a.jpg",
  },
  {
    id: 896,
    job_id: "rngl195",
    job_title: "Promotor (Jabodetabek)",
    company: "PT Arkana Advance Technology (Bang Jamin)",
    category: "Promotor",
    location: "Setiabudi, Jakarta Selatan, DKI Jakarta, Indonesia",
    work_type: "Penuh Waktu",
    working_type: "Tidak ditampilkan",
    salary: "Tidak ditampilkan",
    experience: "Kurang dari setahun",
    skills: "Interpersonal Skills",
    study_requirement: "SMA/SMK",
    description:
      "Pria/Wanita, Usia 18-40 tahun, Pendidikan min. SMA/sederajat, Sehat jasmani dan rohani, Memiliki keterampilan interpersonal yang baik, Mahir menggunakan gadget dan aplikasi online, Memiliki kendaraan motor dan SIM C, Handle area Jabodetabek",
    link: "https://glints.com/id/opportunities/jobs/promotor-jabodetabek/c92a8f27-c5cc-4081-bf4c-850ab1abde7d?utm_referrer=explore",
    link_image:
      "https://images.glints.com/unsafe/glints-dashboard.s3.amazonaws.com/company-logo/ad03feb592aafe65d3c4d592b478800a.jpg",
  },
  {
    id: 897,
    job_id: "rngl196",
    job_title: "Sales Otomotif",
    company: "PT Adi Surya Amartya Sukoharjo",
    category: "Target Oriented",
    location: "Banjarmasin Tengah, Banjarmasin, Kalimantan Selatan, Indonesia",
    work_type: "Penuh Waktu",
    working_type: "Tidak ditampilkan",
    salary: "Rp2jt-Rp2,5jt",
    experience: "Kurang dari setahun",
    skills: "Tidak ditampilkan",
    study_requirement: "SMA/SMK",
    description:
      "Pria, Pendidikan minimal SMA/SMK, Ulet dan suka pekerjaan lapangan, Punya motor dan SIM C/A, Bersedia keluar kota, Target oriented, Untuk Area Kalimantan Timur, Berpengalaman di bidang Spareart mobil minimal 1 tahun",
    link: "https://glints.com/id/opportunities/jobs/sales-otomotif/5a29c327-1573-4020-b773-a2d3563c2803?utm_referrer=explore",
    link_image:
      "https://images.glints.com/unsafe/glints-dashboard.s3.amazonaws.com/company-logo/008fbb966edc27b089eaad8e22366eca.jpg",
  },
  {
    id: 898,
    job_id: "rngl197",
    job_title: "Marketing Executive",
    company: "Pusat Bekam Ruqyah",
    category: "Market Research",
    location: "Tambun Selatan, Bekasi, Jawa Barat, Indonesia",
    work_type: "Kontrak",
    working_type: "Tidak ditampilkan",
    salary: "Rp5,8jt",
    experience: "Kurang dari setahun",
    skills: "Komunikasi Pemasaran, Manajemen Pemasaran, Penelitian Pasar",
    study_requirement: "SMA/SMK",
    description:
      "Mengembangkan rencana merek dan strategi pemasaran yang efektif dan inovatif untuk membangun merek yang kuat, Menciptakan pesan merek yang akan meningkatkan penjualan, Mengembangkan strategi merek untuk meningkatkan citra merek, Mengelola agensi dan klien",
    link: "https://glints.com/id/opportunities/jobs/marketing-executive/b8ae5215-fc86-4063-a6ba-eb5f66878134?utm_referrer=explore",
    link_image:
      "https://images.glints.com/unsafe/glints-dashboard.s3.amazonaws.com/company-logo/f1fe6c7f7957fd8855b783fbd9a7c1b1.jfif",
  },
  {
    id: 899,
    job_id: "rngl198",
    job_title: "Asisten Apoteker",
    company: "Rumah Sakit Umum Andhika",
    category: "Healthcare",
    location: "Jagakarsa, Jakarta Selatan, DKI Jakarta, Indonesia",
    work_type: "Penuh Waktu",
    working_type: "Tidak ditampilkan",
    salary: "Tidak ditampilkan",
    experience: "Kurang dari setahun",
    skills: "Kesehatan, Farmasi, Perhatian terhadap Detail",
    study_requirement: "Sarjana (S1)",
    link: "https://glints.com/id/opportunities/jobs/asisten-apoteker/2147cea1-3bb9-4243-8d55-4014bfa48311?utm_referrer=explore",
    link_image:
      "https://images.glints.com/unsafe/glints-dashboard.s3.amazonaws.com/company-logo/3f5e2489418da662f3e1462325be6943.png",
  },
  {
    id: 900,
    job_id: "rngl199",
    job_title: "Graphic Design - Internship",
    company: "Involuntir",
    category: "Adobe Illustrator",
    location: "Genteng, Surabaya, Jawa Timur, Indonesia",
    work_type: "Magang",
    working_type: "Tidak ditampilkan",
    salary: "Tidak ditampilkan",
    experience: "Kurang dari setahun",
    skills: "Desain Grafis, Adobe Illustrator, Adobe Photoshop",
    study_requirement: "Sarjana (S1)",
    description:
      "Membuat konsep desain dan mengimplementasikan, Review dan koreksi pada final project, Riset desain dan konsep sesuai trend terkini, Mengembangkan, merancang, dan membuat ide",
    link: "https://glints.com/id/opportunities/jobs/graphic-design-internship/17a9ee26-bb92-4582-941f-a0de50d4b5c8?utm_referrer=explore",
    link_image:
      "https://images.glints.com/unsafe/glints-dashboard.s3.amazonaws.com/company-logo/374e3f2e72dfd14ae6850a48895b384d.png",
  },
  {
    id: 901,
    job_id: "rngl200",
    job_title: "Content Creator - Internship",
    company: "Involuntir",
    category: "Content Creation",
    location: "Genteng, Surabaya, Jawa Timur, Indonesia",
    work_type: "Magang",
    working_type: "Tidak ditampilkan",
    salary: "Tidak ditampilkan",
    experience: "Kurang dari setahun",
    skills: "Berbicara di Depan Umum, Pembuatan Konten, Pengeditan Video",
    study_requirement: "Sarjana (S1)",
    description:
      "Membuat content planning dan mengembangkan strategi media sosial;, Melakukan riset algoritma di beberapa social media platform;, Menjadi talent pada platform Tiktok maupun Instagram;, Melakukan sosialisasi campaign/fundraising secara online;, Membuat Dail",
    link: "https://glints.com/id/opportunities/jobs/content-creator-internship/816662bb-9dae-4bc6-8d89-a85fb194cc57?utm_referrer=explore",
    link_image:
      "https://images.glints.com/unsafe/glints-dashboard.s3.amazonaws.com/company-logo/374e3f2e72dfd14ae6850a48895b384d.png",
  },
  {
    id: 902,
    job_id: "rngl201",
    job_title: "Technical Writer",
    company: "PT. Ebdesk Teknologi",
    category: "Hadoop",
    location: "Pondok Aren, Tangerang Selatan, Banten, Indonesia",
    work_type: "Kontrak",
    working_type: "Tidak ditampilkan",
    salary: "Rp4,5jt-Rp6,7jt",
    experience: "Kurang dari setahun",
    skills: "GIT, Jira, Metodologi Agile, Hadoop, Software Documentation",
    study_requirement: "Sarjana (S1)",
    description:
      "Develop user guides, API docs, and technical specifications., Collaborate with tech teams for accurate content., Review and edit documentation for clarity and consistency., Provide user assistance through FAQs and tutorials., Collaborate with cross-functi",
    link: "https://glints.com/id/opportunities/jobs/technical-writer/ac7cf0b9-f088-486d-95ac-28edd1b699e0?utm_referrer=explore",
    link_image:
      "https://images.glints.com/unsafe/glints-dashboard.s3.amazonaws.com/company-logo/34181ed7097881edee812f4d9b1e9e4d.png",
  },
  {
    id: 903,
    job_id: "rngl202",
    job_title: "Security & Satpam",
    company: "PT. Wira Surya Mandiri",
    category: "Security Management",
    location: "Cikarang Utara, Bekasi, Jawa Barat, Indonesia",
    work_type: "Penuh Waktu",
    working_type: "Tidak ditampilkan",
    salary: "Tidak ditampilkan",
    experience: "Kurang dari setahun",
    skills: "KTA Security, Keamanan Informasi, Manajemen Keamanan",
    study_requirement: "SMA/SMK",
    description:
      "Melakukan patroli rutin di area perusahaan untuk menjaga keamanan., Mengontrol akses masuk dan keluar karyawan, pengunjung, dan kendaraan., Menangani situasi keamanan seperti pencurian, tindakan vandalisme, atau insiden keamanan lainnya., Menanggapi pangg",
    link: "https://glints.com/id/opportunities/jobs/security-and-satpam/4ea3cd7d-7e7f-4e1c-aa5f-475b5f85f347?utm_referrer=explore",
    link_image:
      "https://images.glints.com/unsafe/glints-dashboard.s3.amazonaws.com/company-logo/96a7ec7ed619959a18856cb2a7b1a3b0.png",
  },
  {
    id: 904,
    job_id: "rngl203",
    job_title: "Housekeeper",
    company: "Aldeoz Grand Kancana Bali",
    category: "Hospitality Management",
    location: "Badung",
    work_type: "Penuh Waktu",
    working_type: "Tidak ditampilkan",
    salary: "Tidak ditampilkan",
    experience: "Kurang dari setahun",
    skills: "Kerja Tim, Manajemen Hospitalitas, Kemampuan Komunikasi",
    study_requirement: "SMA/SMK",
    link: "https://glints.com/id/opportunities/jobs/housekeeper/a23d7b41-e26c-4ae1-8ebc-eb77142b5b92?utm_referrer=explore",
    link_image:
      "https://images.glints.com/unsafe/glints-dashboard.s3.amazonaws.com/company-logo/e65a0aa1cb471ffa428b25558c080eca.jpeg",
  },
  {
    id: 905,
    job_id: "rngl204",
    job_title: "Guru Olah Raga",
    company: "Millennia World School",
    category: "Teaching",
    location: "Ciputat, Tangerang Selatan, Banten, Indonesia",
    work_type: "Penuh Waktu",
    working_type: "Tidak ditampilkan",
    salary: "Tidak ditampilkan",
    experience: "Kurang dari setahun",
    skills: "Kerja Tim, Berbicara di Depan Umum, Pengajaran",
    study_requirement: "Diploma (D1 - D4)",
    description:
      "Membuat perencanaan pembelajaran, Memberikan aktivitas pelajaran dan penilaian kepada siswa, Membuat laporan nilai dan perkembangan siswa, Mengikuti kegiatan akademik maupun non akademik yang diadakan oleh sekolah, Bertanggung jawab atas pemenuhan pengaja",
    link: "https://glints.com/id/opportunities/jobs/guru-olah-raga/2b67211c-29f1-42a7-ba7c-b0b2e408b3a9?utm_referrer=explore",
    link_image:
      "https://images.glints.com/unsafe/glints-dashboard.s3.amazonaws.com/company-logo/3810b5a729a827d8c2ca089200368126.png",
  },
  {
    id: 906,
    job_id: "rngl205",
    job_title: "Import Officer (Mandarin Translator)",
    company: "Kokai Indo Abadi",
    category: "Good Comunication Skill",
    location: "Batuceper, Tangerang, Banten, Indonesia",
    work_type: "Penuh Waktu",
    working_type: "Tidak ditampilkan",
    salary: "Rp5jt-Rp10jt",
    experience: "Kurang dari setahun",
    skills: "Tidak ditampilkan",
    study_requirement: "Diploma (D1 - D4)",
    description:
      "Reviewing Drawing and Bill Of Material requirements., Preparing PQ, technical reports, analyses, budgets, risk assessment, and other documents., Create purchase and procurement reports (daily, weekly, monthly, and yearly), Create a purchase PO, Accept req",
    link: "https://glints.com/id/opportunities/jobs/import-officer-mandarin-translator/2c1ab192-8bab-4a3b-9115-b08b786473de?utm_referrer=explore",
    link_image:
      "https://images.glints.com/unsafe/glints-dashboard.s3.amazonaws.com/company-logo/3b3f14e59807df1a46f162562cf0106e.png",
  },
  {
    id: 907,
    job_id: "rngl206",
    job_title: "Beauty Advisor / Consultant",
    company: "PT Mega Wasta Prima",
    category: "Pharmaceutical Sales",
    location: "Klojen, Malang, Jawa Timur, Indonesia",
    work_type: "Penuh Waktu",
    working_type: "Tidak ditampilkan",
    salary: "Rp4jt-Rp5jt",
    experience: "Kurang dari setahun",
    skills:
      "Pemasaran Produk, Penjualan Farmasi, Penjualan dan Pemasaran, Manajemen Pengetahuan",
    study_requirement: "SMA/SMK",
    description:
      "menjawab pertanyaan konsumen tentang produk, teknik pengaplikasian atau penggunaannya, berkonsultasi dengan konsumen untuk menentukan tipe kulit, masalah kesehatan kulitnya, dan preferensi gaya yang diinginkannya, merekomendasikan produk yang sesuai denga",
    link: "https://glints.com/id/opportunities/jobs/beauty-advisor-consultant/6b74c256-4b55-4c3f-8490-300cef0303b7?utm_referrer=explore",
    link_image:
      "https://images.glints.com/unsafe/glints-dashboard.s3.amazonaws.com/company-logo/e7430536bfe4be8a717d91aeb6d07d3e.png",
  },
  {
    id: 908,
    job_id: "rngl207",
    job_title: "Distributor",
    company: "PT. Jaya Pratama Groserindo Bali",
    category: "Multitasking",
    location: "Denpasar Selatan, Denpasar, Bali, Indonesia",
    work_type: "Penuh Waktu",
    working_type: "Tidak ditampilkan",
    salary: "Rp2,9jt-Rp3jt",
    experience: "Kurang dari setahun",
    skills: "Perangkat Keras Komputer, Kemampuan Komunikasi, Multitasking",
    study_requirement: "SMA/SMK",
    link: "https://glints.com/id/opportunities/jobs/distributor/1c2dfc33-c697-4395-a0b2-a0ca2cac6cef?utm_referrer=explore",
    link_image:
      "https://images.glints.com/unsafe/glints-dashboard.s3.amazonaws.com/company-logo/34bcdfe10130dff85176c2ff498297eb.jpg",
  },
  {
    id: 909,
    job_id: "rngl208",
    job_title: "SEO Specialist",
    company: "Discover Banyuwangi",
    category: "Google Analytics",
    location: "Licin, Banyuwangi, Jawa Timur, Indonesia",
    work_type: "Penuh Waktu",
    working_type: "Tidak ditampilkan",
    salary: "Rp3jt-Rp4jt",
    experience: "Kurang dari setahun",
    skills: "Google Keyword Planner, Laporan Manajemen, Google Analytics",
    study_requirement: "Sarjana (S1)",
    description:
      "program in HTML, CSS and JavaScript to ensure the site is accessible and easy to follow and for increased interaction with visitors - this may involve working on video and PDFs, run pay-per-click (PPC) campaigns to increase revenue through sponsored onlin",
    link: "https://glints.com/id/opportunities/jobs/seo-specialist/82b5571d-0a3d-471a-a933-56002c1cbe56?utm_referrer=explore",
    link_image:
      "https://images.glints.com/unsafe/glints-dashboard.s3.amazonaws.com/company-logo/56d6c73a737da66fe5d39a19a424d95c.png",
  },
  {
    id: 910,
    job_id: "rngl209",
    job_title: "Odoo Functional Consultant Internship",
    company: "PT Nusantara Sukses Teknologi (Nusatek.id)",
    category: "Communication Skills",
    location: "Mampang Prapatan, Jakarta Selatan, DKI Jakarta, Indonesia",
    work_type: "Magang",
    working_type: "Tidak ditampilkan",
    salary: "Tidak ditampilkan",
    experience: "Kurang dari setahun",
    skills: "Analytical Skills, Kemampuan Komunikasi",
    study_requirement: "Sarjana (S1)",
    link: "https://glints.com/id/opportunities/jobs/odoo-functional-consultant-internship/e8edc05b-6449-4b56-bfea-938f25777a58?utm_referrer=explore",
    link_image:
      "https://images.glints.com/unsafe/glints-dashboard.s3.amazonaws.com/company-logo/ba00c3d547740f6e62711108d9725d40.jpg",
  },
  {
    id: 911,
    job_id: "rngl210",
    job_title: "Staff Adventure",
    company: "Toya Devasya Geopark Resort & Villas",
    category: "Leadership Development",
    location: "Kintamani, Bangli, Bali, Indonesia",
    work_type: "Penuh Waktu",
    working_type: "Tidak ditampilkan",
    salary: "Tidak ditampilkan",
    experience: "Kurang dari setahun",
    skills: "Pengembangan Kepemimpinan, Kerja Tim, Kemampuan Komunikasi",
    study_requirement: "SMA/SMK",
    link: "https://glints.com/id/opportunities/jobs/staff-adventure/03b57489-3864-4f1f-b22c-305af898f5ef?utm_referrer=explore",
    link_image:
      "https://images.glints.com/unsafe/glints-dashboard.s3.amazonaws.com/company-logo/1b7ebac8443e0cd8b0467e118a0cca15.png",
  },
  {
    id: 912,
    job_id: "rngl211",
    job_title: "Admin Accounting",
    company: "YUMICO",
    category: "Microsoft Office",
    location: "Denpasar Timur, Denpasar, Bali, Indonesia",
    work_type: "Penuh Waktu",
    working_type: "Tidak ditampilkan",
    salary: "Rp2jt-Rp3jt",
    experience: "Kurang dari setahun",
    skills: "Akuntansi, Microsoft Word, Microsoft Office",
    study_requirement: "Sarjana (S1)",
    link: "https://glints.com/id/opportunities/jobs/admin-accounting/8b576e89-662c-4a81-a8ba-6c01597e3b24?utm_referrer=explore",
    link_image:
      "https://images.glints.com/unsafe/glints-dashboard.s3.amazonaws.com/company-logo/64c1304b393b24bc65c4886418c86e28.jpeg",
  },
  {
    id: 913,
    job_id: "rngl212",
    job_title: "Guru ipa",
    company: "Sekolah Islam Shafta",
    category: "Microsoft Office",
    location: "Sambikerep, Surabaya, Jawa Timur, Indonesia",
    work_type: "Penuh Waktu",
    working_type: "Tidak ditampilkan",
    salary: "Rp1jt-Rp2jt",
    experience: "Kurang dari setahun",
    skills: "Microsoft Word, Microsoft Office, Manajemen Waktu",
    study_requirement: "Sarjana (S1)",
    description:
      "Membuat perencanaan pembelajaran, Memberikan aktivitas pelajaran dan penilaian kepada siswa, Membuat laporan nilai dan perkembangan siswa, Mengikuti kegiatan akademik maupun non akademik yang diadakan oleh sekolah, Bertanggung jawab atas pemenuhan pengaja",
    link: "https://glints.com/id/opportunities/jobs/guru-ipa/4feeee17-d3ae-40b5-9752-1f05061534cf?utm_referrer=explore",
    link_image:
      "https://images.glints.com/unsafe/glints-dashboard.s3.amazonaws.com/company-logo/b1d710bcf1e4edeef0f1320069b623ab.jpg",
  },
  {
    id: 914,
    job_id: "rngl213",
    job_title: "Marketing Communication (Internship)",
    company: "Baleton Laksana Tirta",
    category: "Positive Attitude",
    location: "Penjaringan, Jakarta Utara, DKI Jakarta, Indonesia",
    work_type: "Magang",
    working_type: "Tidak ditampilkan",
    salary: "Tidak ditampilkan",
    experience: "Kurang dari setahun",
    skills: "Digital Marketing, Kemampuan Komunikasi, Sikap Positif",
    study_requirement: "Sarjana (S1)",
    description:
      "CURRENT ENROLLMENT IN AN UNDERGRADUATE COURSE FOR MARKETING COMMUNICATION OR SIMILAR FIELD., EASY GOING AND EXCELLENT PROBLEM SOLVING SKILLS., FAMILIAR WITH DIGITAL CAMPAIGN & KNOW HOW DIGITAL MEDIA WORKS., EXCELLENT VERBAL AND WRITTEN COMMUNICATION SKILL",
    link: "https://glints.com/id/opportunities/jobs/marketing-communication-internship/6928fd5e-b033-40c7-85ba-0a3019aaed67?utm_referrer=explore",
    link_image:
      "https://images.glints.com/unsafe/glints-dashboard.s3.amazonaws.com/company-logo/28a6798ada6edcc77f682aeccc1c9e3e.jpg",
  },
  {
    id: 915,
    job_id: "rngl214",
    job_title: "Sales Personal Loan Kediri",
    company: "PT Padma Raharja Sentosa Jawa Timur",
    category: "Sales and Marketing",
    location: "Kediri Kota, Kediri, Jawa Timur, Indonesia",
    work_type: "Penuh Waktu",
    working_type: "Tidak ditampilkan",
    salary: "Tidak ditampilkan",
    experience: "Kurang dari setahun",
    skills:
      "Komunikasi Pemasaran, Penjualan dan Pemasaran, Kemampuan Komunikasi",
    study_requirement: "SMA/SMK",
    link: "https://glints.com/id/opportunities/jobs/sales-personal-loan-kediri/75302f31-e867-4e27-8a81-4460be58fc8b?utm_referrer=explore",
    link_image:
      "https://images.glints.com/unsafe/glints-dashboard.s3.amazonaws.com/company-logo/16a3bf854c847a800c2c80f8cfa961a3.png",
  },
  {
    id: 916,
    job_id: "rngl215",
    job_title: "Sales Personal Loan Mojokerto",
    company: "PT Padma Raharja Sentosa Jawa Timur",
    category: "Sales and Marketing",
    location: "Magersari, Mojokerto, Jawa Timur, Indonesia",
    work_type: "Penuh Waktu",
    working_type: "Tidak ditampilkan",
    salary: "Tidak ditampilkan",
    experience: "Kurang dari setahun",
    skills:
      "Komunikasi Pemasaran, Penjualan dan Pemasaran, Kemampuan Komunikasi",
    study_requirement: "SMA/SMK",
    link: "https://glints.com/id/opportunities/jobs/sales-personal-loan-mojokerto/1bf5bbf4-76c2-4b62-9505-074b46f19413?utm_referrer=explore",
    link_image:
      "https://images.glints.com/unsafe/glints-dashboard.s3.amazonaws.com/company-logo/16a3bf854c847a800c2c80f8cfa961a3.png",
  },
  {
    id: 917,
    job_id: "rngl216",
    job_title: "Sales Personal Loan Gresik",
    company: "PT Padma Raharja Sentosa Jawa Timur",
    category: "Sales and Marketing",
    location: "Gresik, Gresik, Jawa Timur, Indonesia",
    work_type: "Penuh Waktu",
    working_type: "Tidak ditampilkan",
    salary: "Tidak ditampilkan",
    experience: "Kurang dari setahun",
    skills:
      "Komunikasi Pemasaran, Penjualan dan Pemasaran, Kemampuan Komunikasi",
    study_requirement: "SMA/SMK",
    link: "https://glints.com/id/opportunities/jobs/sales-personal-loan-gresik/e58d05de-f6fd-4121-92e9-89062d7d742e?utm_referrer=explore",
    link_image:
      "https://images.glints.com/unsafe/glints-dashboard.s3.amazonaws.com/company-logo/16a3bf854c847a800c2c80f8cfa961a3.png",
  },
  {
    id: 918,
    job_id: "rngl217",
    job_title: "Sales Personal Loan Sidoarjo",
    company: "PT Padma Raharja Sentosa Jawa Timur",
    category: "Sales and Marketing",
    location: "Sidoarjo, Sidoarjo, Jawa Timur, Indonesia",
    work_type: "Penuh Waktu",
    working_type: "Tidak ditampilkan",
    salary: "Tidak ditampilkan",
    experience: "Kurang dari setahun",
    skills:
      "Komunikasi Pemasaran, Penjualan dan Pemasaran, Kemampuan Komunikasi",
    study_requirement: "SMA/SMK",
    link: "https://glints.com/id/opportunities/jobs/sales-personal-loan-sidoarjo/089ea1f8-1ebe-49ee-a098-28ffcdc799a4?utm_referrer=explore",
    link_image:
      "https://images.glints.com/unsafe/glints-dashboard.s3.amazonaws.com/company-logo/16a3bf854c847a800c2c80f8cfa961a3.png",
  },
  {
    id: 919,
    job_id: "rngl218",
    job_title: "Sales Personal Loan Surabaya",
    company: "PT Padma Raharja Sentosa Jawa Timur",
    category: "Sales and Marketing",
    location: "Wonokromo, Surabaya, Jawa Timur, Indonesia",
    work_type: "Penuh Waktu",
    working_type: "Tidak ditampilkan",
    salary: "Tidak ditampilkan",
    experience: "Kurang dari setahun",
    skills:
      "Komunikasi Pemasaran, Penjualan dan Pemasaran, Kemampuan Komunikasi",
    study_requirement: "SMA/SMK",
    link: "https://glints.com/id/opportunities/jobs/sales-personal-loan-surabaya/61e0a756-c2e4-461a-8d1e-f2bf155c4c29?utm_referrer=explore",
    link_image:
      "https://images.glints.com/unsafe/glints-dashboard.s3.amazonaws.com/company-logo/16a3bf854c847a800c2c80f8cfa961a3.png",
  },
  {
    id: 920,
    job_id: "rngl219",
    job_title: "Crew/Helpher",
    company: "Mama Noor",
    category: "Cooking",
    location: "Wonokromo, Surabaya, Jawa Timur, Indonesia",
    work_type: "Penuh Waktu",
    working_type: "Tidak ditampilkan",
    salary: "Tidak ditampilkan",
    experience: "Kurang dari setahun",
    skills: "Tidak ditampilkan",
    study_requirement: "SMA/SMK",
    description:
      "Laki-laki/Perempuan, Usia 19 - 27 tahun, Untuk wanita diutamakan yang berhijab, Bisa bekerja full time dan shift, Memiliki kemampuan customer service dan komunikasi yang baik, Terbiasa menggunakan komputer, Memiliki kemampuan berhitung yang baik",
    link: "https://glints.com/id/opportunities/jobs/crew-helpher/41a8bf90-3cb1-42cc-aa53-3ccdb018d087?utm_referrer=explore",
    link_image:
      "https://images.glints.com/unsafe/glints-dashboard.s3.amazonaws.com/company-logo/png",
  },
  {
    id: 921,
    job_id: "rngl220",
    job_title: "Cashier",
    company: "Mama Noor",
    category: "Cashier",
    location: "Wonokromo, Surabaya, Jawa Timur, Indonesia",
    work_type: "Penuh Waktu",
    working_type: "Tidak ditampilkan",
    salary: "Tidak ditampilkan",
    experience: "Kurang dari setahun",
    skills: "Tidak ditampilkan",
    study_requirement: "SMA/SMK",
    description:
      "Laki-laki/Perempuan, Usia 19 - 27 tahun, Untuk wanita diutamakan yang berhijab, Bisa bekerja full time dan shift, Memiliki kemampuan customer service dan komunikasi yang baik, Terbiasa menggunakan komputer, Memiliki kemampuan berhitung yang baik",
    link: "https://glints.com/id/opportunities/jobs/cashier/2d68cf9b-e003-4d5f-b604-2d2e93b9f59c?utm_referrer=explore",
    link_image:
      "https://images.glints.com/unsafe/glints-dashboard.s3.amazonaws.com/company-logo/png",
  },
  {
    id: 922,
    job_id: "rngl221",
    job_title: "Tentor Fisika SMA",
    company: "Bimbel Youth Educational Centre",
    category: "Critical Thinking",
    location: "Kemantren Wirobrajan, Yogyakarta, DI Yogyakarta, Indonesia",
    work_type: "Paruh Waktu",
    working_type: "Tidak ditampilkan",
    salary: "Rp100rb-Rp2jt",
    experience: "Kurang dari setahun",
    skills: "Berpikir Kritis, Berbicara di Depan Umum, Pengajaran",
    study_requirement: "Sarjana (S1)",
    link: "https://glints.com/id/opportunities/jobs/tentor-fisika-sma/620cfee0-efbb-44e9-aa35-5bce46c0f179?utm_referrer=explore",
    link_image:
      "https://images.glints.com/unsafe/glints-dashboard.s3.amazonaws.com/company-logo/a4be6f8b16686fbfe8a9b273acb27a55.png",
  },
  {
    id: 923,
    job_id: "rngl222",
    job_title: "Fashion Designer",
    company: "Deary Castle Official",
    category: "Videography",
    location: "Jatisampurna, Bekasi, Jawa Barat, Indonesia",
    work_type: "Magang",
    working_type: "Tidak ditampilkan",
    salary: "Tidak ditampilkan",
    experience: "Kurang dari setahun",
    skills: "Penata Gaya Busana, Kemampuan Komunikasi, Fotografi, Videografi",
    study_requirement: "SMA/SMK",
    description:
      "Menyukai dunia fashion, Update tentang trend dan perkembang fashion, Dapat menggunakan aplikasi desain, Memiliki keterampilan fotografi dan videografi, Mampu bekerja sama dengan tim menciptakan produk baru",
    link: "https://glints.com/id/opportunities/jobs/fashion-designer/799e6d95-eef9-4cd2-b47b-cd289e5dbbce?utm_referrer=explore",
    link_image:
      "https://images.glints.com/unsafe/glints-dashboard.s3.amazonaws.com/company-logo/152f13c65164e9aff7f9ab7775082ecb.png",
  },
  {
    id: 924,
    job_id: "rngl223",
    job_title: "Marketing Researcher",
    company: "Deary Castle Official",
    category: "Market Research",
    location: "Jatisampurna, Bekasi, Jawa Barat, Indonesia",
    work_type: "Magang",
    working_type: "Tidak ditampilkan",
    salary: "Tidak ditampilkan",
    experience: "Kurang dari setahun",
    skills: "Penelitian Pasar, Penelitian Kuantitatif, Keterampilan Presentasi",
    study_requirement: "SMA/SMK",
    description:
      "Mengerti mengenai riset pasar, Mampu menganalisis data-data pasar, Memahami target audience, Memahami update trend pasar",
    link: "https://glints.com/id/opportunities/jobs/marketing-researcher/b7900914-0d5f-4005-a769-363fc941c8ba?utm_referrer=explore",
    link_image:
      "https://images.glints.com/unsafe/glints-dashboard.s3.amazonaws.com/company-logo/152f13c65164e9aff7f9ab7775082ecb.png",
  },
  {
    id: 925,
    job_id: "rngl224",
    job_title: "Content Creator",
    company: "Deary Castle Official",
    category: "Photo Editing",
    location: "Jatisampurna, Bekasi, Jawa Barat, Indonesia",
    work_type: "Magang",
    working_type: "Tidak ditampilkan",
    salary: "Tidak ditampilkan",
    experience: "Kurang dari setahun",
    skills:
      "Pengeditan Foto, Pembuatan Konten, Pengeditan Video, Adobe Photoshop",
    study_requirement: "SMA/SMK",
    description:
      "Dapat membuat konten yang menarik dan memikat agar mencapai target audience, Dapat menulis artikel, membuat foto dan video, Mengerti mengenai SEO dan strategi konten, Menguasai public speaking dengan baik dan mampu live produk",
    link: "https://glints.com/id/opportunities/jobs/content-creator/f45e9967-ae05-4e3c-ad66-c39b87116c07?utm_referrer=explore",
    link_image:
      "https://images.glints.com/unsafe/glints-dashboard.s3.amazonaws.com/company-logo/152f13c65164e9aff7f9ab7775082ecb.png",
  },
  {
    id: 926,
    job_id: "rngl225",
    job_title: "SPG/SPB Crew Outlet",
    company: "Livana Spikoe",
    category: "Communication Skills",
    location: "Kebon Jeruk, Jakarta Barat, DKI Jakarta, Indonesia",
    work_type: "Penuh Waktu",
    working_type: "Tidak ditampilkan",
    salary: "Tidak ditampilkan",
    experience: "Kurang dari setahun",
    skills: "Kemampuan Komunikasi, Manajemen Penjualan, Administrasi",
    study_requirement: "SMA/SMK",
    description:
      "Wanita/Pria maksimal 25 tahun (Belum menikah), Pendidikan minimal SMA/Sederajat, Tidak sedang berkuliah, Fresh graduate/pengalaman, Rapi & Berpenampilan menarik, Sehat jasmani dan rohani, Jujur, disiplin, bisa bekerja tim, Bersedia ditempatkan diseluruh c",
    link: "https://glints.com/id/opportunities/jobs/spg-spb-crew-outlet/229b163e-db6d-44b8-ab16-60b3247537dd?utm_referrer=explore",
    link_image:
      "https://images.glints.com/unsafe/glints-dashboard.s3.amazonaws.com/company-logo/02e9784590e5f4ec386219485d660aa9.png",
  },
  {
    id: 927,
    job_id: "rngl226",
    job_title: "Sales Executive",
    company: "Suzuki MT Haryono",
    category: "Sales and Marketing",
    location: "Jatinegara, Jakarta Timur, DKI Jakarta, Indonesia",
    work_type: "Penuh Waktu",
    working_type: "Tidak ditampilkan",
    salary: "Tidak ditampilkan",
    experience: "Kurang dari setahun",
    skills: "Penjualan dan Pemasaran, Penjualan B2C, Kemampuan Komunikasi",
    study_requirement: "Diploma (D1 - D4)",
    description:
      "Jujur & Serius, Berpenampilan Serius, Memiliki kendaraan pribadi, Minimal memiliki SIM C, Pendidikan Minimal D3, Usia 20-35 tahun, Ulet dan pantang menyerah, Target Oriented, Punya motivasi untuk sukses, Aktif Sosial Media",
    link: "https://glints.com/id/opportunities/jobs/sales-executive/76c5657a-17ab-49c9-96b4-1342421f9b07?utm_referrer=explore",
    link_image:
      "https://images.glints.com/unsafe/glints-dashboard.s3.amazonaws.com/company-logo/cf1faaf4fb1133896ea9eb0aac74db44.png",
  },
  {
    id: 928,
    job_id: "rngl227",
    job_title: "Steward Part Time Weekend",
    company: "Reanda Bernardi - Audit, Tax, M&A , Advisory",
    category: "Customer Satisfaction",
    location: "Kelapa Dua, Tangerang, Banten, Indonesia",
    work_type: "Harian",
    working_type: "Tidak ditampilkan",
    salary: "Tidak ditampilkan",
    experience: "Kurang dari setahun",
    skills: "Pelayanan Pelanggan, Kepuasan Pelanggan, Manajemen Restoran",
    study_requirement: "SMA/SMK",
    link: "https://glints.com/id/opportunities/jobs/steward-part-time-weekend/13b539e2-9ed2-4724-886b-57ec5a67884f?utm_referrer=explore",
    link_image:
      "https://images.glints.com/unsafe/glints-dashboard.s3.amazonaws.com/company-logo/e0ca29ba78d6a0688488a3a64ff47caf.jpg",
  },
  {
    id: 929,
    job_id: "rngl228",
    job_title: "SPG Hajatan Ponorogo",
    company: "PT Siprama Komunindo Jawa Timur",
    category: "Sales and Marketing",
    location: "Ponorogo, Ponorogo, Jawa Timur, Indonesia",
    work_type: "Penuh Waktu",
    working_type: "Tidak ditampilkan",
    salary: "Rp2jt-Rp2,2jt",
    experience: "Kurang dari setahun",
    skills:
      "Komunikasi Pemasaran, Penjualan dan Pemasaran, Kemampuan Komunikasi",
    study_requirement: "SMA/SMK",
    description:
      "Wanita, Usia maksimal 35 tahun, Memiliki HP Android minimal RAM 4, Mempunyai motor dan SIM C, Pengalaman sales/kerja lapangan",
    link: "https://glints.com/id/opportunities/jobs/spg-hajatan-ponorogo/481a0935-7f9e-433c-a6bc-4d60c816ce43?utm_referrer=explore",
    link_image:
      "https://images.glints.com/unsafe/glints-dashboard.s3.amazonaws.com/company-logo/ac396436178a13fad5e345a4762a3706.jpeg",
  },
  {
    id: 930,
    job_id: "rngl229",
    job_title: "SPG Hajatan Bangkalan",
    company: "PT Siprama Komunindo Jawa Timur",
    category: "Sales and Marketing",
    location: "Bangkalan, Bangkalan, Jawa Timur, Indonesia",
    work_type: "Penuh Waktu",
    working_type: "Tidak ditampilkan",
    salary: "Tidak ditampilkan",
    experience: "Kurang dari setahun",
    skills:
      "Komunikasi Pemasaran, Penjualan dan Pemasaran, Kemampuan Komunikasi",
    study_requirement: "SMA/SMK",
    description:
      "Wanita, Usia maksimal 35 tahun, Memiliki HP Android minimal RAM 4, Mempunyai motor dan SIM C, Pengalaman sales/kerja lapangan",
    link: "https://glints.com/id/opportunities/jobs/spg-hajatan-bangkalan/cbf37fe5-88b4-44ce-9a91-bec4c03b14f2?utm_referrer=explore",
    link_image:
      "https://images.glints.com/unsafe/glints-dashboard.s3.amazonaws.com/company-logo/ac396436178a13fad5e345a4762a3706.jpeg",
  },
  {
    id: 931,
    job_id: "rngl230",
    job_title: "SPG Hajatan",
    company: "PT Siprama Komunindo Jawa Timur",
    category: "Sales and Marketing",
    location: "Magetan, Magetan, Jawa Timur, Indonesia",
    work_type: "Penuh Waktu",
    working_type: "Tidak ditampilkan",
    salary: "Rp2jt-Rp2,2jt",
    experience: "Kurang dari setahun",
    skills:
      "Komunikasi Pemasaran, Penjualan dan Pemasaran, Kemampuan Komunikasi",
    study_requirement: "SMA/SMK",
    description:
      "Wanita, Usia maksimal 35 tahun, Memiliki HP Android minimal RAM 4, Mempunyai motor dan SIM C, Pengalaman sales/kerja lapangan",
    link: "https://glints.com/id/opportunities/jobs/spg-hajatan/0d67d651-7dff-4946-a394-bc3d7d276fbe?utm_referrer=explore",
    link_image:
      "https://images.glints.com/unsafe/glints-dashboard.s3.amazonaws.com/company-logo/ac396436178a13fad5e345a4762a3706.jpeg",
  },
  {
    id: 932,
    job_id: "rngl231",
    job_title: "Customer Engineer Kediri",
    company: "PT Siprama Komunindo Jawa Timur",
    category: "Telecommunications",
    location: "Kediri Kota, Kediri, Jawa Timur, Indonesia",
    work_type: "Penuh Waktu",
    working_type: "Tidak ditampilkan",
    salary: "Tidak ditampilkan",
    experience: "Kurang dari setahun",
    skills: "Hubungan Pelanggan, Bahasa Inggris, Telekomunikasi",
    study_requirement: "Diploma (D1 - D4)",
    description:
      "Laki-laki / Perempuan, Maksimal 25 Tahun, Pendidikan Min D3 T. Komputer/Telekomunikasi, T. Elektro, T. Mesin, T. Mekatronika/Elektromekanikal, atau setara., Fresh graduate diperbolehkan melamar, Mahir berbahasa Inggris dan Indonesia, Mempunyai Motor dan S",
    link: "https://glints.com/id/opportunities/jobs/customer-engineer-kediri/d8c85a3f-d98e-45cd-ade9-eb4c28462ab4?utm_referrer=explore",
    link_image:
      "https://images.glints.com/unsafe/glints-dashboard.s3.amazonaws.com/company-logo/ac396436178a13fad5e345a4762a3706.jpeg",
  },
  {
    id: 933,
    job_id: "rngl232",
    job_title: "Customer Engineer Malang",
    company: "PT Siprama Komunindo Jawa Timur",
    category: "Telecommunications",
    location: "Blimbing, Malang, Jawa Timur, Indonesia",
    work_type: "Penuh Waktu",
    working_type: "Tidak ditampilkan",
    salary: "Tidak ditampilkan",
    experience: "Kurang dari setahun",
    skills: "Hubungan Pelanggan, Bahasa Inggris, Telekomunikasi",
    study_requirement: "Diploma (D1 - D4)",
    description:
      "Laki-laki / Perempuan, Maksimal 25 Tahun, Pendidikan Min D3 T. Komputer/Telekomunikasi, T. Elektro, T. Mesin, T. Mekatronika/Elektromekanikal, atau setara., Fresh graduate diperbolehkan melamar, Mahir berbahasa Inggris dan Indonesia, Mempunyai Motor dan S",
    link: "https://glints.com/id/opportunities/jobs/customer-engineer-malang/00213a55-7e6b-4baa-86ad-28bae170d996?utm_referrer=explore",
    link_image:
      "https://images.glints.com/unsafe/glints-dashboard.s3.amazonaws.com/company-logo/ac396436178a13fad5e345a4762a3706.jpeg",
  },
  {
    id: 934,
    job_id: "rngl233",
    job_title: "Customer Engineer",
    company: "PT Siprama Komunindo Jawa Timur",
    category: "Telecommunications",
    location: "Rungkut, Surabaya, Jawa Timur, Indonesia",
    work_type: "Penuh Waktu",
    working_type: "Tidak ditampilkan",
    salary: "Tidak ditampilkan",
    experience: "Kurang dari setahun",
    skills: "Hubungan Pelanggan, Bahasa Inggris, Telekomunikasi",
    study_requirement: "Diploma (D1 - D4)",
    description:
      "Laki-laki / Perempuan, Maksimal 25 Tahun, Pendidikan Min D3 T. Komputer/Telekomunikasi, T. Elektro, T. Mesin, T. Mekatronika/Elektromekanikal, atau setara., Fresh graduate diperbolehkan melamar, Mahir berbahasa Inggris dan Indonesia, Mempunyai Motor dan S",
    link: "https://glints.com/id/opportunities/jobs/customer-engineer/05874d78-c97e-41d6-b427-d7988889bb51?utm_referrer=explore",
    link_image:
      "https://images.glints.com/unsafe/glints-dashboard.s3.amazonaws.com/company-logo/ac396436178a13fad5e345a4762a3706.jpeg",
  },
  {
    id: 935,
    job_id: "rngl234",
    job_title: "Psikolog Cimahi",
    company: "PT PRIMA KARYA SARANA SEJAHTERA BANDUNG",
    category: "Sales and Marketing",
    location: "Cimahi Selatan, Cimahi, Jawa Barat, Indonesia",
    work_type: "Penuh Waktu",
    working_type: "Tidak ditampilkan",
    salary: "Tidak ditampilkan",
    experience: "Kurang dari setahun",
    skills: "SAP, Penjualan dan Pemasaran, Manajemen Penjualan",
    study_requirement: "Diploma (D1 - D4)",
    link: "https://glints.com/id/opportunities/jobs/psikolog-cimahi/75ddf858-f167-4191-b933-9e0698c7565b?utm_referrer=explore",
    link_image:
      "https://images.glints.com/unsafe/glints-dashboard.s3.amazonaws.com/company-logo/03fac11d6157a78198697a0c99861dd9.jpeg",
  },
  {
    id: 936,
    job_id: "rngl235",
    job_title: "Psikolog kab Bandung",
    company: "PT PRIMA KARYA SARANA SEJAHTERA BANDUNG",
    category: "Sales Management",
    location: "Margaasih, Bandung, Jawa Barat, Indonesia",
    work_type: "Penuh Waktu",
    working_type: "Tidak ditampilkan",
    salary: "Tidak ditampilkan",
    experience: "Kurang dari setahun",
    skills: "Penjualan dan Pemasaran, Manajemen Penjualan, Operasi Penjualan",
    study_requirement: "Diploma (D1 - D4)",
    link: "https://glints.com/id/opportunities/jobs/psikolog-kab-bandung/2e998e20-5d3e-47c3-bc09-d7e82509aa2b?utm_referrer=explore",
    link_image:
      "https://images.glints.com/unsafe/glints-dashboard.s3.amazonaws.com/company-logo/03fac11d6157a78198697a0c99861dd9.jpeg",
  },
  {
    id: 937,
    job_id: "rngl236",
    job_title: "SPB / SPG Akuisisi Cimahi",
    company: "PT JANE INTAN PERMATA BANDUNG",
    category: "Sales Operations",
    location: "Cimahi Selatan, Cimahi, Jawa Barat, Indonesia",
    work_type: "Penuh Waktu",
    working_type: "Tidak ditampilkan",
    salary: "Tidak ditampilkan",
    experience: "Kurang dari setahun",
    skills: "Penjualan dan Pemasaran, Manajemen Penjualan, Operasi Penjualan",
    study_requirement: "SMA/SMK",
    link: "https://glints.com/id/opportunities/jobs/spb-spg-akuisisi-cimahi/b66b380f-9530-4039-989b-ba78cc58392e?utm_referrer=explore",
    link_image:
      "https://images.glints.com/unsafe/glints-dashboard.s3.amazonaws.com/company-logo/bff3484b7df29bfe553a94f8efffbd0f.png",
  },
  {
    id: 938,
    job_id: "rngl237",
    job_title: "SPB / SPG Akuisisi Kab Bandung Barat",
    company: "PT JANE INTAN PERMATA BANDUNG",
    category: "Sales and Marketing",
    location: "Gununghalu, Bandung Barat, Jawa Barat, Indonesia",
    work_type: "Penuh Waktu",
    working_type: "Tidak ditampilkan",
    salary: "Tidak ditampilkan",
    experience: "Kurang dari setahun",
    skills: "SAP, Penjualan dan Pemasaran, Manajemen Penjualan",
    study_requirement: "Diploma (D1 - D4)",
    link: "https://glints.com/id/opportunities/jobs/spb-spg-akuisisi-kab-bandung-barat/67484e5f-5472-4f59-8ee7-4adb0879d5d2?utm_referrer=explore",
    link_image:
      "https://images.glints.com/unsafe/glints-dashboard.s3.amazonaws.com/company-logo/bff3484b7df29bfe553a94f8efffbd0f.png",
  },
  {
    id: 939,
    job_id: "rngl238",
    job_title: "SPB / SPG Akuisisi Kab Bandung",
    company: "PT JANE INTAN PERMATA BANDUNG",
    category: "Sales Operations",
    location: "Kertasari, Bandung, Jawa Barat, Indonesia",
    work_type: "Penuh Waktu",
    working_type: "Tidak ditampilkan",
    salary: "Tidak ditampilkan",
    experience: "Kurang dari setahun",
    skills: "Penjualan dan Pemasaran, Manajemen Penjualan, Operasi Penjualan",
    study_requirement: "SMA/SMK",
    description:
      "Mengidentifikasi dan menghubungi prospek potensial di area yang ditugaskan., Mempromosikan dan menjual produk dan layanan perusahaan kepada pelanggan potensial., Membangun dan menjaga hubungan bisnis yang baik dengan pelanggan yang ada., Mencapai target p",
    link: "https://glints.com/id/opportunities/jobs/spb-spg-akuisisi-kab-bandung/fcf710f7-d625-4365-9039-a7731efd673c?utm_referrer=explore",
    link_image:
      "https://images.glints.com/unsafe/glints-dashboard.s3.amazonaws.com/company-logo/bff3484b7df29bfe553a94f8efffbd0f.png",
  },
  {
    id: 940,
    job_id: "rngl239",
    job_title: "SPB / SPG Akuisisi Bandung",
    company: "PT JANE INTAN PERMATA BANDUNG",
    category: "Sales and Marketing",
    location: "Sumur Bandung, Bandung, Jawa Barat, Indonesia",
    work_type: "Penuh Waktu",
    working_type: "Tidak ditampilkan",
    salary: "Rp2jt-Rp2jt",
    experience: "Kurang dari setahun",
    skills: "SAP, Penjualan dan Pemasaran, Manajemen Penjualan",
    study_requirement: "Diploma (D1 - D4)",
    link: "https://glints.com/id/opportunities/jobs/spb-spg-akuisisi-bandung/10404fdc-3702-4cd0-a23c-8d97f9b56fa8?utm_referrer=explore",
    link_image:
      "https://images.glints.com/unsafe/glints-dashboard.s3.amazonaws.com/company-logo/bff3484b7df29bfe553a94f8efffbd0f.png",
  },
  {
    id: 941,
    job_id: "rngl240",
    job_title: "Sales Akuisisi Merchant Cimahi",
    company: "PT JANE INTAN PERMATA BANDUNG",
    category: "Sales Operations",
    location: "Cimahi Selatan, Cimahi, Jawa Barat, Indonesia",
    work_type: "Penuh Waktu",
    working_type: "Tidak ditampilkan",
    salary: "Tidak ditampilkan",
    experience: "Kurang dari setahun",
    skills: "Penjualan dan Pemasaran, Manajemen Penjualan, Operasi Penjualan",
    study_requirement: "Diploma (D1 - D4)",
    link: "https://glints.com/id/opportunities/jobs/sales-akuisisi-merchant-cimahi/8df95451-745d-4e40-abe7-47330af73c82?utm_referrer=explore",
    link_image:
      "https://images.glints.com/unsafe/glints-dashboard.s3.amazonaws.com/company-logo/bff3484b7df29bfe553a94f8efffbd0f.png",
  },
  {
    id: 942,
    job_id: "rngl241",
    job_title: "Sales Akuisisi Merchant Kab Bandung Barat",
    company: "PT JANE INTAN PERMATA BANDUNG",
    category: "Sales and Marketing",
    location: "Cipatat, Bandung Barat, Jawa Barat, Indonesia",
    work_type: "Penuh Waktu",
    working_type: "Tidak ditampilkan",
    salary: "Tidak ditampilkan",
    experience: "Kurang dari setahun",
    skills: "SAP, Penjualan dan Pemasaran, Manajemen Penjualan",
    study_requirement: "Diploma (D1 - D4)",
    link: "https://glints.com/id/opportunities/jobs/sales-akuisisi-merchant-kab-bandung-barat/ad38ec51-359e-4a84-908f-4604602fef34?utm_referrer=explore",
    link_image:
      "https://images.glints.com/unsafe/glints-dashboard.s3.amazonaws.com/company-logo/bff3484b7df29bfe553a94f8efffbd0f.png",
  },
  {
    id: 943,
    job_id: "rngl242",
    job_title: "Sales Akuisisi Merchant Kab Bandung",
    company: "PT JANE INTAN PERMATA BANDUNG",
    category: "Sales Operations",
    location: "Kertasari, Bandung, Jawa Barat, Indonesia",
    work_type: "Penuh Waktu",
    working_type: "Tidak ditampilkan",
    salary: "Tidak ditampilkan",
    experience: "Kurang dari setahun",
    skills: "Penjualan dan Pemasaran, Manajemen Penjualan, Operasi Penjualan",
    study_requirement: "Diploma (D1 - D4)",
    link: "https://glints.com/id/opportunities/jobs/sales-akuisisi-merchant-kab-bandung/41f2924a-3245-4cf0-b222-4d2cb0fee478?utm_referrer=explore",
    link_image:
      "https://images.glints.com/unsafe/glints-dashboard.s3.amazonaws.com/company-logo/bff3484b7df29bfe553a94f8efffbd0f.png",
  },
  {
    id: 944,
    job_id: "rngl243",
    job_title: "Sales Akuisisi Merchant Bandung",
    company: "PT JANE INTAN PERMATA BANDUNG",
    category: "Salesforce",
    location: "Babakan Ciparay, Bandung, Jawa Barat, Indonesia",
    work_type: "Penuh Waktu",
    working_type: "Tidak ditampilkan",
    salary: "Tidak ditampilkan",
    experience: "Kurang dari setahun",
    skills: "SAP, Manajemen Penjualan, Salesforce",
    study_requirement: "Diploma (D1 - D4)",
    link: "https://glints.com/id/opportunities/jobs/sales-akuisisi-merchant-bandung/f74c8bfc-fde2-4d1c-942b-6fb4ce6c026b?utm_referrer=explore",
    link_image:
      "https://images.glints.com/unsafe/glints-dashboard.s3.amazonaws.com/company-logo/bff3484b7df29bfe553a94f8efffbd0f.png",
  },
  {
    id: 945,
    job_id: "rngl244",
    job_title: "Sales Eksekutif QRIS Merchant Kab Bandung",
    company: "PT JANE INTAN PERMATA BANDUNG",
    category: "Sales and Marketing",
    location: "Margaasih, Bandung, Jawa Barat, Indonesia",
    work_type: "Penuh Waktu",
    working_type: "Tidak ditampilkan",
    salary: "Tidak ditampilkan",
    experience: "Kurang dari setahun",
    skills: "SAP, Penjualan dan Pemasaran, Manajemen Penjualan",
    study_requirement: "Diploma (D1 - D4)",
    link: "https://glints.com/id/opportunities/jobs/sales-eksekutif-qris-merchant-kab-bandung/805a7453-ee9a-4160-9973-43543c6468f5?utm_referrer=explore",
    link_image:
      "https://images.glints.com/unsafe/glints-dashboard.s3.amazonaws.com/company-logo/bff3484b7df29bfe553a94f8efffbd0f.png",
  },
  {
    id: 946,
    job_id: "rngl245",
    job_title: "Sales Eksekutif QRIS Merchant Kota Cimahi",
    company: "PT JANE INTAN PERMATA BANDUNG",
    category: "Sales Operations",
    location: "Cimahi Selatan, Cimahi, Jawa Barat, Indonesia",
    work_type: "Penuh Waktu",
    working_type: "Tidak ditampilkan",
    salary: "Tidak ditampilkan",
    experience: "Kurang dari setahun",
    skills: "Penjualan dan Pemasaran, Manajemen Penjualan, Operasi Penjualan",
    study_requirement: "Diploma (D1 - D4)",
    link: "https://glints.com/id/opportunities/jobs/sales-eksekutif-qris-merchant-kota-cimahi/b6b9a186-d699-4ee3-9214-a9bf00c560ce?utm_referrer=explore",
    link_image:
      "https://images.glints.com/unsafe/glints-dashboard.s3.amazonaws.com/company-logo/bff3484b7df29bfe553a94f8efffbd0f.png",
  },
  {
    id: 947,
    job_id: "rngl246",
    job_title: "Sales Eksekutif QRIS Merchant Bandung",
    company: "PT JANE INTAN PERMATA BANDUNG",
    category: "Sales Operations",
    location: "Astana Anyar, Bandung, Jawa Barat, Indonesia",
    work_type: "Penuh Waktu",
    working_type: "Tidak ditampilkan",
    salary: "Tidak ditampilkan",
    experience: "Kurang dari setahun",
    skills: "Penjualan dan Pemasaran, Manajemen Penjualan, Operasi Penjualan",
    study_requirement: "Diploma (D1 - D4)",
    link: "https://glints.com/id/opportunities/jobs/sales-eksekutif-qris-merchant-bandung/39e18960-df28-4465-b0c6-5589c5dd89f6?utm_referrer=explore",
    link_image:
      "https://images.glints.com/unsafe/glints-dashboard.s3.amazonaws.com/company-logo/bff3484b7df29bfe553a94f8efffbd0f.png",
  },
  {
    id: 948,
    job_id: "rngl247",
    job_title: "SPV aktifasi Qris Kab Bandung",
    company: "PT JANE INTAN PERMATA BANDUNG",
    category: "Sales Operations",
    location: "Kertasari, Bandung, Jawa Barat, Indonesia",
    work_type: "Penuh Waktu",
    working_type: "Tidak ditampilkan",
    salary: "Tidak ditampilkan",
    experience: "Kurang dari setahun",
    skills: "Penjualan dan Pemasaran, Manajemen Penjualan, Operasi Penjualan",
    study_requirement: "Diploma (D1 - D4)",
    link: "https://glints.com/id/opportunities/jobs/spv-aktifasi-qris-kab-bandung/96d8d761-5a5e-46ec-80fa-14b1e1e343f6?utm_referrer=explore",
    link_image:
      "https://images.glints.com/unsafe/glints-dashboard.s3.amazonaws.com/company-logo/bff3484b7df29bfe553a94f8efffbd0f.png",
  },
  {
    id: 949,
    job_id: "rngl248",
    job_title: "SPV aktifasi Qris Cimahi",
    company: "PT JANE INTAN PERMATA BANDUNG",
    category: "Sales Operations",
    location: "Cimahi Selatan, Cimahi, Jawa Barat, Indonesia",
    work_type: "Penuh Waktu",
    working_type: "Tidak ditampilkan",
    salary: "Tidak ditampilkan",
    experience: "Kurang dari setahun",
    skills: "Penjualan dan Pemasaran, Manajemen Penjualan, Operasi Penjualan",
    study_requirement: "Diploma (D1 - D4)",
    link: "https://glints.com/id/opportunities/jobs/spv-aktifasi-qris-cimahi/c444434b-3683-4632-9bea-9c569467620b?utm_referrer=explore",
    link_image:
      "https://images.glints.com/unsafe/glints-dashboard.s3.amazonaws.com/company-logo/bff3484b7df29bfe553a94f8efffbd0f.png",
  },
  {
    id: 950,
    job_id: "rngl249",
    job_title: "SPV aktifasi Qris Bandung",
    company: "PT JANE INTAN PERMATA BANDUNG",
    category: "Sales and Marketing",
    location: "Babakan Ciparay, Bandung, Jawa Barat, Indonesia",
    work_type: "Penuh Waktu",
    working_type: "Tidak ditampilkan",
    salary: "Tidak ditampilkan",
    experience: "Kurang dari setahun",
    skills: "SAP, Penjualan dan Pemasaran, Manajemen Penjualan",
    study_requirement: "Diploma (D1 - D4)",
    link: "https://glints.com/id/opportunities/jobs/spv-aktifasi-qris-bandung/0d074b3a-609b-401f-b4b2-195bda4aec0c?utm_referrer=explore",
    link_image:
      "https://images.glints.com/unsafe/glints-dashboard.s3.amazonaws.com/company-logo/bff3484b7df29bfe553a94f8efffbd0f.png",
  },
  {
    id: 951,
    job_id: "rngl250",
    job_title: "account officer consumer Kab Bandung Barat",
    company: "PT JANE INTAN PERMATA BANDUNG",
    category: "Sales Operations",
    location: "Cisarua, Bandung Barat, Jawa Barat, Indonesia",
    work_type: "Penuh Waktu",
    working_type: "Tidak ditampilkan",
    salary: "Tidak ditampilkan",
    experience: "Kurang dari setahun",
    skills: "Penjualan dan Pemasaran, Manajemen Penjualan, Operasi Penjualan",
    study_requirement: "Diploma (D1 - D4)",
    link: "https://glints.com/id/opportunities/jobs/account-officer-consumer-kab-bandung-barat/2ac14768-d25a-42f6-a7d8-4366054dac03?utm_referrer=explore",
    link_image:
      "https://images.glints.com/unsafe/glints-dashboard.s3.amazonaws.com/company-logo/bff3484b7df29bfe553a94f8efffbd0f.png",
  },
  {
    id: 952,
    job_id: "rngl251",
    job_title: "account officer consumer Kab Bandung",
    company: "PT JANE INTAN PERMATA BANDUNG",
    category: "Sales and Marketing",
    location: "Kertasari, Bandung, Jawa Barat, Indonesia",
    work_type: "Penuh Waktu",
    working_type: "Tidak ditampilkan",
    salary: "Tidak ditampilkan",
    experience: "Kurang dari setahun",
    skills: "SAP, Penjualan dan Pemasaran, Manajemen Penjualan",
    study_requirement: "Diploma (D1 - D4)",
    link: "https://glints.com/id/opportunities/jobs/account-officer-consumer-kab-bandung/1c1b261c-7a34-4634-acbf-f632af3a5ff4?utm_referrer=explore",
    link_image:
      "https://images.glints.com/unsafe/glints-dashboard.s3.amazonaws.com/company-logo/bff3484b7df29bfe553a94f8efffbd0f.png",
  },
  {
    id: 953,
    job_id: "rngl252",
    job_title: "account officer consumer Kota Cimahi",
    company: "PT JANE INTAN PERMATA BANDUNG",
    category: "Sales and Marketing",
    location: "Cimahi Tengah, Cimahi, Jawa Barat, Indonesia",
    work_type: "Penuh Waktu",
    working_type: "Tidak ditampilkan",
    salary: "Tidak ditampilkan",
    experience: "Kurang dari setahun",
    skills: "SAP, Penjualan dan Pemasaran, Manajemen Penjualan",
    study_requirement: "Diploma (D1 - D4)",
    link: "https://glints.com/id/opportunities/jobs/account-officer-consumer-kota-cimahi/d38600b6-36db-4909-8f2f-fe0000d1e690?utm_referrer=explore",
    link_image:
      "https://images.glints.com/unsafe/glints-dashboard.s3.amazonaws.com/company-logo/bff3484b7df29bfe553a94f8efffbd0f.png",
  },
  {
    id: 954,
    job_id: "rngl253",
    job_title: "account officer consumer Bandung",
    company: "PT JANE INTAN PERMATA BANDUNG",
    category: "Sales and Marketing",
    location: "Sumur Bandung, Bandung, Jawa Barat, Indonesia",
    work_type: "Penuh Waktu",
    working_type: "Tidak ditampilkan",
    salary: "Tidak ditampilkan",
    experience: "Kurang dari setahun",
    skills: "SAP, Penjualan dan Pemasaran, Manajemen Penjualan",
    study_requirement: "Diploma (D1 - D4)",
    link: "https://glints.com/id/opportunities/jobs/account-officer-consumer-bandung/89cbefa2-16c1-4216-9b85-7096385524b6?utm_referrer=explore",
    link_image:
      "https://images.glints.com/unsafe/glints-dashboard.s3.amazonaws.com/company-logo/bff3484b7df29bfe553a94f8efffbd0f.png",
  },
  {
    id: 955,
    job_id: "rngl254",
    job_title: "account officer consumer Kab Cirebon",
    company: "PT JANE INTAN PERMATA BANDUNG",
    category: "Sales and Marketing",
    location: "Losari, Cirebon, Jawa Barat, Indonesia",
    work_type: "Penuh Waktu",
    working_type: "Tidak ditampilkan",
    salary: "Tidak ditampilkan",
    experience: "Kurang dari setahun",
    skills: "SAP, Penjualan dan Pemasaran, Manajemen Penjualan",
    study_requirement: "Diploma (D1 - D4)",
    link: "https://glints.com/id/opportunities/jobs/account-officer-consumer-kab-cirebon/629e6ccd-8efd-4edb-8f8f-b7422dee0f78?utm_referrer=explore",
    link_image:
      "https://images.glints.com/unsafe/glints-dashboard.s3.amazonaws.com/company-logo/bff3484b7df29bfe553a94f8efffbd0f.png",
  },
  {
    id: 956,
    job_id: "rngl255",
    job_title: "CEO Office Associate",
    company: "Segari",
    category: "Analytical Skills",
    location: "Ciputat, Tangerang Selatan, Banten, Indonesia",
    work_type: "Penuh Waktu",
    working_type: "Tidak ditampilkan",
    salary: "Tidak ditampilkan",
    experience: "Kurang dari setahun",
    skills: "Analytical Skills, SQL, Keterampilan Pemecahan Masalah",
    study_requirement: "Sarjana (S1)",
    link: "https://glints.com/id/opportunities/jobs/ceo-office-associate/e6cdc12f-2f1e-4c55-ae88-8df11df0f63f?utm_referrer=explore",
    link_image:
      "https://images.glints.com/unsafe/glints-dashboard.s3.amazonaws.com/company-logo/cbfea2502055e62b5fd4ff6c5eeecce2.png",
  },
  {
    id: 957,
    job_id: "rngl256",
    job_title: "account officer consumer Cirebon",
    company: "PT JANE INTAN PERMATA BANDUNG",
    category: "Sales and Marketing",
    location: "Kesambi, Cirebon, Jawa Barat, Indonesia",
    work_type: "Penuh Waktu",
    working_type: "Tidak ditampilkan",
    salary: "Tidak ditampilkan",
    experience: "Kurang dari setahun",
    skills: "SAP, Penjualan dan Pemasaran, Manajemen Penjualan",
    study_requirement: "Diploma (D1 - D4)",
    link: "https://glints.com/id/opportunities/jobs/account-officer-consumer-cirebon/88d8e25d-c734-4ed3-af5c-fe74dd918cf0?utm_referrer=explore",
    link_image:
      "https://images.glints.com/unsafe/glints-dashboard.s3.amazonaws.com/company-logo/bff3484b7df29bfe553a94f8efffbd0f.png",
  },
  {
    id: 958,
    job_id: "rngl257",
    job_title: "Creative Designer",
    company: "PT TAZE LAB INTERNATIONAL",
    category: "Creative Design",
    location: "Kebon Jeruk, Jakarta Barat, DKI Jakarta, Indonesia",
    work_type: "Penuh Waktu",
    working_type: "Tidak ditampilkan",
    salary: "Tidak ditampilkan",
    experience: "Kurang dari setahun",
    skills: "Kerja Tim, Desain Grafis, Desain Kreatif",
    study_requirement: "Diploma (D1 - D4)",
    description:
      "Bachelor’s degree in Graphic Design, Fine Arts, or a related field (open for undergraduate and fresh graduate), Demonstrated experience in Adobe Creative Suite, including Photoshop, Illustrator, and InDesign, Great 3D design skills (Blender and all sorts ",
    link: "https://glints.com/id/opportunities/jobs/creative-designer/6dfd3bbb-08c9-4711-b6ae-40bb26e15a49?utm_referrer=explore",
    link_image:
      "https://images.glints.com/unsafe/glints-dashboard.s3.amazonaws.com/company-logo/bbab43ff4434f4e8d5caeb3d6e8fb395.png",
  },
  {
    id: 959,
    job_id: "rngl258",
    job_title: "Guru Les Private di Medan Petisah (kelas 6 SD Sant",
    company: "Private Tutor Indonesia (Guru Les Seluruh Indonesia)",
    category: "mengajar matematika",
    location: "Medan Petisah, Medan, Sumatera Utara, Indonesia",
    work_type: "Paruh Waktu",
    working_type: "Tidak ditampilkan",
    salary: "Tidak ditampilkan",
    experience: "Kurang dari setahun",
    skills: "Tidak ditampilkan",
    study_requirement: "Diploma (D1 - D4)",
    link: "https://glints.com/id/opportunities/jobs/guru-les-private-di-medan-petisah-kelas-6-sd-santo-nicholas/c8de6420-2221-4876-a9c9-860a5de89cd3?utm_referrer=explore",
    link_image:
      "https://images.glints.com/unsafe/glints-dashboard.s3.amazonaws.com/company-logo/41330c0b3692a33bd6e188b791cfbbdd.jpeg",
  },
  {
    id: 960,
    job_id: "rngl259",
    job_title: "Graphic Designer",
    company: "Clandestin",
    category: "Adobe Indesign",
    location: "Bekasi Barat, Bekasi, Jawa Barat, Indonesia",
    work_type: "Magang",
    working_type: "Tidak ditampilkan",
    salary: "Rp1jt-Rp1,5jt",
    experience: "Kurang dari setahun",
    skills: "Desain Grafis, Adobe Photoshop",
    study_requirement: "Diploma (D1 - D4)",
    description:
      "Develop graphics and visual layouts for product illustrations, company logos, websites, and advertisements., Work closely with the marketing team, content creators, and product teams to create cohesive designs that reflect our corporate cultures and goals",
    link: "https://glints.com/id/opportunities/jobs/graphic-designer/4cf6bd80-dd23-4606-be07-0e95dcae0020?utm_referrer=explore",
    link_image:
      "https://images.glints.com/unsafe/glints-dashboard.s3.amazonaws.com/company-logo/1b921648cebf092aa71d5050899e46aa.jpeg",
  },
  {
    id: 961,
    job_id: "rngl260",
    job_title: "GURU LES PELAJARAN SEKOLAH AJA 3 SMPdi Sei Agul Me",
    company: "Private Tutor Indonesia (Guru Les Seluruh Indonesia)",
    category: "Teaching High School Science",
    location: "Medan Barat, Medan, Sumatera Utara, Indonesia",
    work_type: "Paruh Waktu",
    working_type: "Tidak ditampilkan",
    salary: "Tidak ditampilkan",
    experience: "Kurang dari setahun",
    skills: "Mengajar IPA SMA, Bahasa Inggris, Matematika",
    study_requirement: "Diploma (D1 - D4)",
    link: "https://glints.com/id/opportunities/jobs/guru-les-pelajaran-sekolah-aja-3-smpdi-sei-agul-medan-125-jumpa/d19b7ba9-c45a-4dda-8730-64239be8fdf0?utm_referrer=explore",
    link_image:
      "https://images.glints.com/unsafe/glints-dashboard.s3.amazonaws.com/company-logo/41330c0b3692a33bd6e188b791cfbbdd.jpeg",
  },
  {
    id: 962,
    job_id: "rngl261",
    job_title: "Intern/Full Time Marketing and Account Support",
    company: "d-ta PROMOTION",
    category: "Sales and Marketing",
    location: "Jatinegara, Jakarta Timur, DKI Jakarta, Indonesia",
    work_type: "Magang",
    working_type: "Tidak ditampilkan",
    salary: "Tidak ditampilkan",
    experience: "Kurang dari setahun",
    skills: "Penjualan dan Pemasaran, Kemampuan Komunikasi, Administrasi",
    study_requirement: "SMA/SMK",
    link: "https://glints.com/id/opportunities/jobs/intern-full-time-marketing-and-account-support/5c539ccb-b42c-4238-a54b-6f7fb8073789?utm_referrer=explore",
    link_image:
      "https://images.glints.com/unsafe/glints-dashboard.s3.amazonaws.com/company-logo/4ba881d3d89fb369eaf2c8a89d1627ab.png",
  },
  {
    id: 963,
    job_id: "rngl262",
    job_title: "Service Advisor",
    company: "PT Prospect Motor",
    category: "Communication Skills",
    location: "Tanjung Redeb, Berau, Kalimantan Timur, Indonesia",
    work_type: "Penuh Waktu",
    working_type: "Tidak ditampilkan",
    salary: "Tidak ditampilkan",
    experience: "Kurang dari setahun",
    skills:
      "Kemampuan Komunikasi, Keterampilan Negosiasi, Keterampilan Pemecahan Masalah",
    study_requirement: "Diploma (D1 - D4)",
    description:
      "Memasukkan data keluhan pelanggan mengenai kondisi kendaraan pelanggan ke komputer., Mengingatkan pelanggan untuk melakukan perawatan berkala berikutnya pada saat selesai perawatan / perbaikan., Menentukan harga dan memberikan diskon pada customer untuk p",
    link: "https://glints.com/id/opportunities/jobs/service-advisor/dd2e5a51-0d2b-4cff-afe0-6c54d0a20b34?utm_referrer=explore",
    link_image:
      "https://images.glints.com/unsafe/glints-dashboard.s3.amazonaws.com/company-logo/97fc12e67020270bf3f3731c80f79321.jpg",
  },
  {
    id: 964,
    job_id: "rngl263",
    job_title: "Data Engineer",
    company: "Pt Kreator Solusi Informasi",
    category: "Data Analysis",
    location: "Cakung, Jakarta Timur, DKI Jakarta, Indonesia",
    work_type: "Penuh Waktu",
    working_type: "Tidak ditampilkan",
    salary: "Rp5jt-Rp5,5jt",
    experience: "Kurang dari setahun",
    skills: "SQL, Power BI",
    study_requirement: "Diploma (D1 - D4)",
    link: "https://glints.com/id/opportunities/jobs/data-engineer/b410b182-30e1-4d88-9588-d3611699998a?utm_referrer=explore",
    link_image:
      "https://images.glints.com/unsafe/glints-dashboard.s3.amazonaws.com/company-logo/100e00d7d73862701aae99912207ca06.png",
  },
  {
    id: 965,
    job_id: "rngl264",
    job_title: "Store Crew",
    company: "PT Global Ritel Digital",
    category: "Interpersonal Skills",
    location: "Senapelan, Pekanbaru, Riau, Indonesia",
    work_type: "Magang",
    working_type: "Tidak ditampilkan",
    salary: "Tidak ditampilkan",
    experience: "Kurang dari setahun",
    skills: "Interpersonal Skills",
    study_requirement: "SMA/SMK",
    description:
      "Minimal pendidikan SMA/SMK sederajat, Lebih disukai memiliki pengalaman menjadi store staff/kasir selama 1 tahun, Bersedia penempatan di Pekanbaru, Wajib berdomisili di Pekanbaru",
    link: "https://glints.com/id/opportunities/jobs/store-crew/75c07032-f8f2-4532-a026-65e5179c951d?utm_referrer=explore",
    link_image:
      "https://images.glints.com/unsafe/glints-dashboard.s3.amazonaws.com/company-logo/a092838d0503f92fda0149c92f38522f.png",
  },
  {
    id: 966,
    job_id: "rngl265",
    job_title: "Host Livestreamer",
    company: "PT AGENCY MSM INTERNATIONAL",
    category: "Interpersonal Communication",
    location: "Cisauk, Tangerang, Banten, Indonesia",
    work_type: "Penuh Waktu",
    working_type: "Tidak ditampilkan",
    salary: "Rp4,5jt-Rp6jt",
    experience: "Kurang dari setahun",
    skills:
      "Kemampuan Komunikasi, Komunikasi Interpersonal, Keterampilan Komunikasi",
    study_requirement: "SMA/SMK",
    description:
      "Menghadirkan siaran langsung yang menarik dan menghibur kepada audiens., Berinteraksi secara aktif dengan audiens melalui chat dan komentar., Menyampaikan konten dengan jelas dan memikat menggunakan kemampuan berbicara yang baik., Memahami tren dan topik ",
    link: "https://glints.com/id/opportunities/jobs/host-livestreamer/bde50bb4-b673-4874-a090-709dc90b573d?utm_referrer=explore",
    link_image:
      "https://images.glints.com/unsafe/glints-dashboard.s3.amazonaws.com/company-logo/f298398a45d2d768f84ef1b174772646.jpeg",
  },
  {
    id: 967,
    job_id: "rngl266",
    job_title: "Sales Executive",
    company: "PT. Bersaudara Inti Corpora",
    category: "Sales and Marketing",
    location: "Kembangan, Jakarta Barat, DKI Jakarta, Indonesia",
    work_type: "Penuh Waktu",
    working_type: "Tidak ditampilkan",
    salary: "Tidak ditampilkan",
    experience: "Kurang dari setahun",
    skills:
      "Komunikasi Pemasaran, Penjualan dan Pemasaran, Kemampuan Komunikasi",
    study_requirement: "Sarjana (S1)",
    description:
      "Melakukan penjualan produk melalui telepon atau online, ecommerce, dll., Mencapai target penjualan perusahaan., Sebagai sales penjualan paper., Handle customer baru untuk wilayah Surabaya dan Jawa Tengah., Menyusun Laporan penjualan., Membuat promosi, mar",
    link: "https://glints.com/id/opportunities/jobs/sales-executive/8d03e755-ed8f-447d-a977-7ccbc4671eaf?utm_referrer=explore",
    link_image:
      "https://images.glints.com/unsafe/glints-dashboard.s3.amazonaws.com/company-logo/8e20402e87394f371407c5d6fca89c27.jpg",
  },
  {
    id: 968,
    job_id: "rngl267",
    job_title: "Marketing Property Freelance",
    company: "The Consultant Property (PT Weida Indah Cemerlang)",
    category: "Sales and Marketing",
    location: "Tigaraksa, Tangerang, Banten, Indonesia",
    work_type: "Paruh Waktu",
    working_type: "Tidak ditampilkan",
    salary: "Tidak ditampilkan",
    experience: "Kurang dari setahun",
    skills:
      "Digital Marketing, Penjualan dan Pemasaran, Berbicara di Depan Umum",
    study_requirement: "SMA/SMK",
    link: "https://glints.com/id/opportunities/jobs/marketing-property-freelance/c62eb056-0aea-4410-a5d2-49be18386604?utm_referrer=explore",
    link_image:
      "https://images.glints.com/unsafe/glints-dashboard.s3.amazonaws.com/company-logo/800b3dd71103a59487084c5a931155b4.jpg",
  },
  {
    id: 969,
    job_id: "rngl268",
    job_title: "Admin Finance",
    company: "Clandestin",
    category: "Microsoft Office",
    location: "Bekasi Selatan, Bekasi, Jawa Barat, Indonesia",
    work_type: "Magang",
    working_type: "Tidak ditampilkan",
    salary: "Rp1jt-Rp1,5jt",
    experience: "Kurang dari setahun",
    skills: "Keuangan Manajerial, Microsoft Office, Administrasi",
    study_requirement: "Diploma (D1 - D4)",
    description:
      "Membuat pembukuan laporan keuangan, Memproses transaksi keuangan perusahaan dan melakukan pencatatan transaksi, Memproses invoice sesuai dengan kebijakan pembayaran secara akurat dan terjadwal, Menganalisa data keuangan dan memberikan bantuan perencanaan,",
    link: "https://glints.com/id/opportunities/jobs/admin-finance/f49a45a4-2c1b-42d9-8995-d47012bad391?utm_referrer=explore",
    link_image:
      "https://images.glints.com/unsafe/glints-dashboard.s3.amazonaws.com/company-logo/1b921648cebf092aa71d5050899e46aa.jpeg",
  },
  {
    id: 970,
    job_id: "rngl269",
    job_title: "Editor ( Base On Project )",
    company: "PT. Ayo Jadi Pengusaha ( SPSO.ID )",
    category: "Photo Editing",
    location: "Cipondoh, Tangerang, Banten, Indonesia",
    work_type: "Kontrak",
    working_type: "Tidak ditampilkan",
    salary: "Tidak ditampilkan",
    experience: "Kurang dari setahun",
    skills: "Kerja Tim, Audio Editing, Pengeditan Foto, Pengeditan Video",
    study_requirement: "Sarjana (S1)",
    description:
      "mengumpulkan semua footage dari berbagai sumber untuk dirapikan sesuai arahan, menyortir materi yang dibutuhkan untuk dipakai dan diolah menjadi video utuh sesuai arahan, menentukan transisi, sentuhan, pewarnaan, juga efek yang akan diterapkan pada video ",
    link: "https://glints.com/id/opportunities/jobs/editor-base-on-project/bcc19c92-9cc8-4347-8325-c2d9e7234197?utm_referrer=explore",
    link_image:
      "https://images.glints.com/unsafe/glints-dashboard.s3.amazonaws.com/company-logo/8d84decc37bb9c50e07f7573a2e985de.png",
  },
];
